repository:
  url                       : hhttps://github.com/xiaoyu12/CS614_Jupyter_notebooks  # Online location of your book
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

#launch_buttons:
#  notebook_interface:  "classic"

launch_buttons:
  colab_url: "https://colab.research.google.com"
